### ISSUE TITLE
I meet promblems when I run multi-preprocess.sh in path /SLfM/AI-Habitat

### ISSUE THREAD

**Issue by qiu-xiaoqi** [IFICL/SLfM#1]
[11:11:54:265809]:[Metadata] AssetAttributesManager.cpp(110)::AssetAttributesManager : Built default primitive asset templates : 12
[11:11:54:266126]:[Metadata] SceneDatasetAttributesManager.cpp(308)::readDatasetJSONCell : "stages.default_attributes" set in Attributes Manager from    JSON.
[11:11:54:266182]:[Metadata] AttributesManagerBase.h(357)::buildAttrSrcPathsFromJSONAndLoad : No Glob path result for /root/sound-spaces/data/scene_da   tasets/data/versioned_data/hm3d-1.0/hm3d/example/00861-GLAQ4DNUx5U/*.basis.glb
[11:11:54:266212]:[Metadata] AttributesManagerBase.h(357)::buildAttrSrcPathsFromJSONAndLoad : No Glob path result for /root/sound-spaces/data/scene_da   tasets/data/versioned_data/hm3d-1.0/hm3d/minival/00800-TEEsavR23oF/*.basis.glb
[11:11:54:266240]:[Metadata] AttributesManagerBase.h(357)::buildAttrSrcPathsFromJSONAndLoad : No Glob path result for /root/sound-spaces/data/scene_da   tasets/data/versioned_data/hm3d-1.0/hm3d/minival/00802-wcojb4TFT35/*.basis.glb

**Comment by IFICL** [comment]
Hi. Would you mind describing the issues in details? As what I can see from the error, it is about Habitat-Sim and Soundspace 2.0. Can you check if you are able to run the mini example from Soundspace 2.0 and make sure the scene data with semantic annotations are available?

**Comment by qiu-xiaoqi** [comment]
Hi，the problem like this：
Traceback (most recent call last):
&nbsp; File "generate_audiosfm.py", line 249, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "generate_audiosfm.py", line 241, in main
&nbsp; &nbsp; run(args, scene_id, settings)
&nbsp; File "generate_audiosfm.py", line 185, in run
&nbsp; &nbsp; camera_sets = sample_rotated_camera_set_with_n_view(args, scene_id, settings)
&nbsp; File "/root/SLfM/Dataset/AI-Habitat/util/camera_pair.py", line 168, in sample_rotated_camera_set_with_n_view
&nbsp; &nbsp; sim = habitat_sim.Simulator(cfg)
&nbsp; File "<attrs generated init habitat_sim.simulator.Simulator&gt;", line 11, in __init__
&nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 118, in __attrs_post_init__
&nbsp; &nbsp; self.__set_from_config(self.config)
&nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 269, in __set_from_config
&nbsp; &nbsp; self._config_backend(config)
&nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 200, in _config_backend
&nbsp; &nbsp; super().__init__(config.sim_cfg, config.metadata_mediator)
AssertionError: ESP_CHECK failed: Missing (at least) one of scene dataset attributes, stage attributes, or dataset scene attributes for scene '/root/sounes/data/scene_datasets/data/versioned_data/hm3d-1.0/hm3d/train/00016-qk9eeNeR4vw/qk9eeNeR4vw.basis.glb'.&nbsp; Likely an invalid scene name.
I have never try to run the mini example from Soundspace 2.0, I will try.Thank you a lot

&nbsp;


※小李飞刀※
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ziyang ***@***.***&gt;; 
发送时间: 2023年8月2日(星期三) 上午10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IFICL/SLfM] I meet promblems when I run multi-preprocess.sh in path /SLfM/AI-Habitat (Issue #1)





 
Hi. Would you mind describing the issues in details? As what I can see from the error, it is about Habitat-Sim and Soundspace 2.0. Can you check if you are able to run the mini example from Soundspace 2.0 and make sure the scene data wirh semantic annotations are available.

**Comment by IFICL** [comment]
> Hi，the problem like this： Traceback (most recent call last): &nbsp; File "generate_audiosfm.py", line 249, in <module&gt; &nbsp; &nbsp; main() &nbsp; File "generate_audiosfm.py", line 241, in main &nbsp; &nbsp; run(args, scene_id, settings) &nbsp; File "generate_audiosfm.py", line 185, in run &nbsp; &nbsp; camera_sets = sample_rotated_camera_set_with_n_view(args, scene_id, settings) &nbsp; File "/root/SLfM/Dataset/AI-Habitat/util/camera_pair.py", line 168, in sample_rotated_camera_set_with_n_view &nbsp; &nbsp; sim = habitat_sim.Simulator(cfg) &nbsp; File "<attrs generated init habitat_sim.simulator.Simulator&gt;", line 11, in __init__ &nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 118, in __attrs_post_init__ &nbsp; &nbsp; self.__set_from_config(self.config) &nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 269, in __set_from_config &nbsp; &nbsp; self._config_backend(config) &nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 200, in _config_backend &nbsp; &nbsp; super().__init__(config.sim_cfg, config.metadata_mediator) AssertionError: ESP_CHECK failed: Missing (at least) one of scene dataset attributes, stage attributes, or dataset scene attributes for scene '/root/sounes/data/scene_datasets/data/versioned_data/hm3d-1.0/hm3d/train/00016-qk9eeNeR4vw/qk9eeNeR4vw.basis.glb'.&nbsp; Likely an invalid scene name. I have never try to run the mini example from Soundspace 2.0, I will try.Thank you a lot &nbsp; ※小李飞刀※ ***@***.*** &nbsp;
> […](#)


As I can tell, this should be the problem of seting up the scene dataset, habitat-smi and soundspace, please refer their repo for detail solution.

**Comment by qiu-xiaoqi** [comment]
Hi， I ran the code：python examples/minimal_example.py
and no error occurred， but after I ran the multi-preprocess， got the same error.
The error seems looks like I didn't have the file /*.basis.glb, but I have the file 'hm3d_annotated_basis.scene_dataset_config.json'.
Whether the /*.basis.glb file will be generated after running multi-preprocess
&nbsp;


※小李飞刀※
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ziyang ***@***.***&gt;; 
发送时间: 2023年8月2日(星期三) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IFICL/SLfM] I meet promblems when I run multi-preprocess.sh in path /SLfM/AI-Habitat (Issue #1)





  
Hi，the problem like this： Traceback (most recent call last): &nbsp; File "generate_audiosfm.py", line 249, in <module&gt; &nbsp; &nbsp; main() &nbsp; File "generate_audiosfm.py", line 241, in main &nbsp; &nbsp; run(args, scene_id, settings) &nbsp; File "generate_audiosfm.py", line 185, in run &nbsp; &nbsp; camera_sets = sample_rotated_camera_set_with_n_view(args, scene_id, settings) &nbsp; File "/root/SLfM/Dataset/AI-Habitat/util/camera_pair.py", line 168, in sample_rotated_camera_set_with_n_view &nbsp; &nbsp; sim = habitat_sim.Simulator(cfg) &nbsp; File "<attrs generated init habitat_sim.simulator.Simulator&gt;", line 11, in init &nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 118, in attrs_post_init &nbsp; &nbsp; self.__set_from_config(self.config) &nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 269, in __set_from_config &nbsp; &nbsp; self._config_backend(config) &nbsp; File "/root/miniconda3/lib/python3.8/site-packages/habitat_sim/simulator.py", line 200, in _config_backend &nbsp; &nbsp; super().init(config.sim_cfg, config.metadata_mediator) AssertionError: ESP_CHECK failed: Missing (at least) one of scene dataset attributes, stage attributes, or dataset scene attributes for scene '/root/sounes/data/scene_datasets/data/versioned_data/hm3d-1.0/hm3d/train/00016-qk9eeNeR4vw/qk9eeNeR4vw.basis.glb'.&nbsp; Likely an invalid scene name. I have never try to run the mini example from Soundspace 2.0, I will try.Thank you a lot &nbsp; ※小李飞刀※ @.*** &nbsp;
 …
  
As I can tell, this should be the problem of seting up the scene dataset, habitat-smi and soundspace, please refer their repo for detail solution.

**Comment by IFICL** [comment]
> Hi， I ran the code：python examples/minimal_example.py and no error occurred， but after I ran the multi-preprocess， got the same error. The error seems looks like I didn't have the file /*.basis.glb, but I have the file 'hm3d_annotated_basis.scene_dataset_config.json'. Whether the /*.basis.glb file will be generated after running multi-preprocess 

For debugging, you can copy the command out to do a single processing debug. For your question,  /*.basis.glb file **will not be** generated after running multi-preprocess. It should be existed. Make sure you download the HM3D semantic dataset in a right way.

**Comment by qiu-xiaoqi** [comment]
This is my code to download the HM3D
python -m habitat_sim.utils.datasets_download --username <api-token-id> --password <api-token-secret> --uids hm3d_semantics
and after I downloaded, there is no /*.basis.glb, only have the /*.semantic.glb and /*.semantic.txt, what should be the uids

**Comment by IFICL** [comment]
> This is my code to download the HM3D python -m habitat_sim.utils.datasets_download --username --password --uids hm3d_semantics and after I downloaded, there is no /_.basis.glb, only have the /_.semantic.glb and /*.semantic.txt, what should be the uids

You only download the semantic labels for HM3D while it doesn't download any original meshes for HM3D. An entire scene should be contained as shown in the screenshots below. 
<img width="242" alt="image" src="https://github.com/IFICL/SLfM/assets/20180169/6c17114e-c70d-4662-889a-6ca2017f3ce5">

Please check the HM3D dataset and codes carefully.

**Comment by qiu-xiaoqi** [comment]
Thank you，now I am downloading the hm3d_train_full

**Comment by IFICL** [comment]
Solved
