### ISSUE TITLE
Platform::WindowlessEglApplication::tryCreateContext(): cannot get default EGL display: EGL_BAD_PARAMETER WindowlessContext: Unable to create windowless context

### ISSUE THREAD

**Issue by qiu-xiaoqi** [IFICL/SLfM#2]
After running the multi-preprocess, I met thist problems:
Platform::WindowlessEglApplication::tryCreateContext(): cannot get default EGL display: EGL_BAD_PARAMETER
WindowlessContext: Unable to create windowless context

**Comment by IFICL** [comment]
For questions about Habitat-smi, please refer to the official repo for help. We are not able to help with issue caused by those.

**Comment by 2927803072** [comment]
> After running the multi-preprocess, I met thist problems: Platform::WindowlessEglApplication::tryCreateContext(): cannot get default EGL display: EGL_BAD_PARAMETER WindowlessContext: Unable to create windowless context

Hello，do you solve it?
