### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by kth0522** [IFICL/SLfM#3]
Could you specify which versions of the LibriSpeech, FMA, and HMD3D datasets I should download?

example) LibriSpeech: original-mp3, FMA: fma-full, hmd3d: hm3d_train_full

**Comment by IFICL** [comment]
Hi, I will answer your question about datasets:
1) LibriSpeech: [test-clean](https://www.openslr.org/resources/12/test-clean.tar.gz) + [train-clean-100](https://www.openslr.org/resources/12/train-clean-100.tar.gz). We resplit them into train/val/test set.
2) FMA: [fma_large.zip](https://os.unil.cloud.switch.ch/fma/fma_large.zip).  We resplit them into train/val/test set.
3) hm3d:  hm3d_train + hm3d_val. You need to download the semantic annotation as well. As a result, you will only have 100 scenes with semantic annotation. It seems HM3D annotated more scenes after that. You can use the [data-split](https://github.com/IFICL/SLfM/tree/master/Dataset/AI-Habitat/data-split) to filter out the scenes that have been used.
