### ISSUE TITLE
can't train on resnet 50

### ISSUE THREAD

**Issue by deBrian07** [IFICL/SLfM#6]
Hello, I was trying the preset training with resnet-50. However, the error shows that there's a key not found error, and a size mismatch error. The only thing I changed was in slfm-pretext.py. I've attached the screenshots below. Please take a look. Thank you so much! 
<img width="932" alt="image" src="https://github.com/IFICL/SLfM/assets/94733710/8cba44fe-4239-49dd-a9da-9ec3ef552a18">
<img width="932" alt="image" src="https://github.com/IFICL/SLfM/assets/94733710/2cf2ecaf-c93d-4c22-9784-52288a117347">

**Comment by IFICL** [comment]
Do you use my provided checkpoints? They are only for ResNet18. If you are retraining the models, pretrain from ImageNet pretrain weights.

**Comment by deBrian07** [comment]
Yes, I'm trying to use slfm-pretext.py to retrain the models with resnet50, and the errors occurred.

**Comment by IFICL** [comment]
Have you had the opportunity to troubleshoot by yourself in order to identify the specific line of code causing this issue? I suspect it's the imagenet pretraining loading issue. Please modify it to meet the torchvision package.

**Comment by IFICL** [comment]
I have tested it on my end, I don't have this issue. I assume it's likely because of the pytorch and torchvision environment update. Please try to fix this by yourself or use the provided environment yml file.
